// <auto-generated />
using M4Movie.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace M4Movie.Api.Data.Migrations
{
    [DbContext(typeof(MovieApiContext))]
    [Migration("20180704112150_Movie")]
    partial class Movie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("M4Movie.Api.Contracts.Movie", b =>
                {
                    b.Property<long>("MovieId");

                    b.Property<double>("AverageVote");

                    b.Property<string>("Comments")
                        .HasMaxLength(750);

                    b.Property<bool>("IsWatchList");

                    b.Property<string>("MovieDescription")
                        .HasMaxLength(750);

                    b.Property<string>("MovieImage")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<int>("VoteCount");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
